/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YcHackernewsRouteImport } from './routes/yc-hackernews'
import { Route as IndexRouteImport } from './routes/index'

const YcHackernewsRoute = YcHackernewsRouteImport.update({
  id: '/yc-hackernews',
  path: '/yc-hackernews',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/yc-hackernews': typeof YcHackernewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/yc-hackernews': typeof YcHackernewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/yc-hackernews': typeof YcHackernewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/yc-hackernews'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/yc-hackernews'
  id: '__root__' | '/' | '/yc-hackernews'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  YcHackernewsRoute: typeof YcHackernewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yc-hackernews': {
      id: '/yc-hackernews'
      path: '/yc-hackernews'
      fullPath: '/yc-hackernews'
      preLoaderRoute: typeof YcHackernewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  YcHackernewsRoute: YcHackernewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
